# Generated by Django 4.0.1 on 2022-02-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('StoreID', models.AutoField(primary_key=True, serialize=False)),
                ('Store_Name', models.CharField(max_length=50)),
                ('Store_category', models.IntegerField()),
                ('User_ID', models.IntegerField()),
                ('Location', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=20)),
                ('Phone', models.CharField(max_length=11)),
                ('Describtion', models.CharField(max_length=500)),
            ],
        ),
    ]
