# Generated by Django 4.0.2 on 2022-02-19 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeID', models.IntegerField()),
                ('orderDate', models.DateTimeField()),
                ('total', models.FloatField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to='cart.checkout')),
            ],
        ),
    ]
