# Generated by Django 4.0.2 on 2022-02-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_checkout_state_alter_checkout_orderdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='state',
        ),
    ]
