# Generated by Django 4.0.2 on 2022-02-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_checkout_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='state',
            field=models.CharField(choices=[('open', 'OPEN'), ('pending', 'PENDING'), ('done', 'DONE')], default='open', max_length=8),
        ),
    ]
